### ISSUE TITLE
Wrong club after registration

### ISSUE THREAD

**Issue by sascha-ng** [XCCup/xccup.net#165]
1. Go to registration page
2. Entered all data, club was "Drachenflieger-Club Trier"
3. Clicked the "Privacy Info" page (which better should open in a separate tab or popup dialog)
4. Go one step back in the browser
5. All previous entered data still remaining except birth date. Didn't check the club selection so I don't know if "Drachenflieger-Club Trier was still selected" or has been reset like the birth date.
6. After registration "1. Pfälzer DGFC" was shown in my profile.

**Comment by JEK58** [comment]
I could not recreate the issue. But anyway: Privacy policy now opens in a modal. (Not live yet)
Datepicker issue in a known bug. I opened a separate issue for better visibility.

**Comment by KaiWissel** [comment]
I could also not recreate the issue.

**Comment by KaiWissel** [comment]
closed
