### ISSUE TITLE
Allow changing club out of season

### ISSUE THREAD

**Issue by sascha-ng** [XCCup/xccup.net#166]
When XCCup is out of season or the pilot has no flights uploaded yet it should be possible to change the club.
I got some questions in the past about that.

**Comment by KaiWissel** [comment]
Backend supports this feature. If not meet backend will throw 403  "It is not possible to change more then once a club within a season"

Needs to be implemented in frontend

**Comment by KaiWissel** [comment]
I am on it ;-)
