### ISSUE TITLE
Max. speed way too high

### ISSUE THREAD

**Issue by sascha-ng** [XCCup/xccup.net#167]
Compare:

https://www.xccup.net/FlugDetails/47188
https://next.xccup.net/flug/46

The max. speed of 234km/h is way too much.

BTW: Do you always calculate speed based on corrdinate distance and time? Some flight instruments (like my Compeo+) have speed sensors which write the current speed to IGC file, so there so no need to calculate speed values.

**Comment by KaiWissel** [comment]
I will look into it.

I was not aware of that functionality. Till now speed will always be calculated over an 30s time frame.

**Comment by KaiWissel** [comment]
Airspeed is located in the extensions object. Key: TAS

**Comment by KaiWissel** [comment]
No further complains.
Issue will be closed.
