### ISSUE TITLE
Editing a flight a second time leads to "Canvas is already in use" error

### ISSUE THREAD

**Issue by sascha-ng** [XCCup/xccup.net#168]
1. Open flight
2. Go to "edit"
3. change a setting and save
4. Flight shows correct (changed) values
5. "Edit" again leads to the following error:

Uh oh .. Error: Canvas is already in use. Chart with ID '1' must be destroyed before the canvas can be reused.

**Comment by JEK58** [comment]
This is known, bugfix is on its way.

**Comment by JEK58** [comment]
fixed
