### ISSUE TITLE
Deleting a flight not possible

### ISSUE THREAD

**Issue by sascha-ng** [XCCup/xccup.net#169]
1. Click on "profile"
2. Then "My flights"
3. Empty list with "Such empty" is shown even I've uploaded one flight

**Comment by JEK58** [comment]
It is possible in flight edit mode via link on /flug/xxx but not implemented in profile yet

**Comment by KaiWissel** [comment]
Looks like this is a rather ux problem

**Comment by JEK58** [comment]
^^

**Comment by KaiWissel** [comment]
It's now possible to delete flights in profile or flight edit mode
