### ISSUE TITLE
Send admin mails

### ISSUE THREAD

**Issue by KaiWissel** [XCCup/xccup.net#303]
Generate once every night an e-mail which summarizes pending requests and flight approvals to the Administrator.

Also send an mail for the "day winner" to Wolf.

**Comment by JEK58** [comment]
I think pending flight request should be mailed immediately to not "hide" the flight from the public after a good flying day.

**Comment by KaiWissel** [comment]
Flight violations: 3072ce8759bdd78d5db7446a251adff43b90fcef
