### ISSUE TITLE
Filter badges are not shown correctly

### ISSUE THREAD

**Issue by JEK58** [XCCup/xccup.net#318]
[https://xccup.net/fluege/?startDate=2022-02-23&endDate=2022-02-24](https://xccup.net/fluege/?startDate=2022-02-23&endDate=2022-02-24)

<img width="1118" alt="Screenshot 2022-02-23 at 20 51 35" src="https://user-images.githubusercontent.com/35194489/155397187-344c41fe-9b03-4f74-bf3a-b3febbeade67.png">

**Comment by KaiWissel** [comment]
it seems that startDate and endDate need to be put on the "blacklist"

**Comment by KaiWissel** [comment]
https://github.com/XCCup/xccup.net/pull/324/commits/6b90e2600bb5631def9b4ec187d18c3c70e2c030
