### ISSUE TITLE
Send airspace remark automatically to admins if submitted on flight upload

### ISSUE THREAD

**Issue by JEK58** [XCCup/xccup.net#321]
Sending a mail to the user asking for an airspace remark is redundant if he already submitted it on upload.

If the airspace remark is submitted, the administrator should receive an email. If it is not submitted, the user should receive an email with a call to action.

**Comment by KaiWissel** [comment]
https://github.com/XCCup/xccup.net/pull/324/commits/81b69986e9985e79fb2651188aee50b4497f5f87
