### ISSUE TITLE
Success popup out of view on large screens

### ISSUE THREAD

**Issue by KaiWissel** [XCCup/xccup.net#340]
User complain:
Didn't recognize the success popup after updating profile.
He uses "a big screen".

_______

Maybe change from toast to alert?

**Comment by JEK58** [comment]
Toasts are a common practice for this. Alerts force the user to interact. Why bother the majority of users with an extra click for some people on large screens. No one forces you to browse the web in fullscreen. And why would you, if you cants even see the whole screen…

**Comment by KaiWissel** [comment]
But it doesn't change the reality that some/many people do.

It's also possible to enlarge the toast.

**Comment by JEK58** [comment]
🥱

**Comment by KaiWissel** [comment]
closed for now
