### ISSUE TITLE
Open new tab in flights table

### ISSUE THREAD

**Issue by KaiWissel** [XCCup/xccup.net#341]
User request:
It should be possible to open a flight in a new tab when right clicking on a flight in a table.

**Comment by JEK58** [comment]
true!

**Comment by JEK58** [comment]
This may not be possibly.

It's not valid html to wrap a <tr> in a <a>.
The current <tr> is JS magic. But the browser only shows link options if a <a> is used.
So we either have to ditch the possibility to click the table row "app like" and introduce a special link button or live with it.

**Comment by KaiWissel** [comment]
https://github.com/XCCup/xccup.net/pull/565

**Comment by KaiWissel** [comment]
9b993d6ffe3801888f2e6534bfe60ad96bbeb4c2
