### ISSUE TITLE
Fix Table header FlightsAll

### ISSUE THREAD

**Issue by KaiWissel** [XCCup/xccup.net#346]
The column "Strecke" on mobile displays distance AND points. The header should be renamed to <<ENTER_CLEVER_NAME_HERE>>

![Screenshot_2022-03-06-20-44-16-597_com opera browser](https://user-images.githubusercontent.com/42967368/157818652-b85ff18e-5071-4159-9eff-536616655eb9.jpg)

**Comment by JEK58** [comment]
Datum also shows takeoff and name the glider;)
I don't see no Problem. Its a "sub info" We could grey it out like the takeoff name.

**Comment by KaiWissel** [comment]
Agreed. We should be consistent. Therefore we should also grey out points. Maybe this helps to differenciate between the two values (see Feedback-Mail from Krick)

**Comment by JEK58** [comment]
Maybe we should switch to Points instead of Distance b/c points are actually more "valuable" than distance in the current ranking system.

**Comment by KaiWissel** [comment]
Agreed that points are more valuable, BUT points are rather abstract. 
On the otherside both values are listed, therefore... Let the time dictate? In other words... wait for user feedback

**Comment by KaiWissel** [comment]
closed for now
