### ISSUE TITLE
Require a minimum track record interval?

### ISSUE THREAD

**Issue by JEK58** [XCCup/xccup.net#368]

**Comment by KaiWissel** [comment]
Hm... Hard question some flights from low takeoffs only last for 2-3 minutes.

What would be a good value? 1 minute? Did we have any problems with short flights?

**Comment by JEK58** [comment]
Interval, not length. eg. 1-5 seconds

**Comment by KaiWissel** [comment]
I see 😄 

But why? I had saw some flights with <1s resolution. They caused some errors in the beginning. But these are now addressed.

**Comment by JEK58** [comment]
So that people don't try to take advantage of an unnecessary long tracking interval. Just an idea…

**Comment by KaiWissel** [comment]
not relevant at the moemtn
