### ISSUE TITLE
Comments: The reply of a reply doesn't get an email notification.

### ISSUE THREAD

**Issue by JEK58** [XCCup/xccup.net#381]
Klasse: The owner get a notification
Danke: the original poster gets a notification
Bitte: The owner of the flight does not get a notification.

Frontend can already handle this in branch: [https://github.com/XCCup/xccup.net/tree/comment-logic-refinement](url)
<img width="520" alt="Screenshot 2022-03-26 at 10 53 57" src="https://user-images.githubusercontent.com/35194489/160234435-871b963b-e1b6-47bb-a46b-088ba203f2ce.png">

**Comment by KaiWissel** [comment]
Owner of flight should always receive an e-mail
