### ISSUE TITLE
Include airspace classes Q and RMZ on map and use RMZ for Airspace violation check

### ISSUE THREAD

**Issue by JEK58** [XCCup/xccup.net#383]

**Comment by KaiWissel** [comment]
Why Q?

**Comment by JEK58** [comment]
Trier Föhren for example is interesting. For social pressure not fly in there. Even if it's legal

**Comment by KaiWissel** [comment]
And admins have to validate this every time? äh... i think not ^^

**Comment by JEK58** [comment]
No, the title says add RMZ and Q to the map. Only use RMZ for violation check. RMZ actually has to be enforced.
Q is just for Information on the map.

**Comment by KaiWissel** [comment]
ed6df85f522e419a4e1c27839a2e912a774b1b87
