### ISSUE TITLE
Prevent tests from removing igc file from the repo

### ISSUE THREAD

**Issue by JEK58** [XCCup/xccup.net#421]

**Comment by KaiWissel** [comment]
@JEK58 more information needed

**Comment by KaiWissel** [comment]
Sometimes cypress will delete an igc file; "Not always"

**Comment by JEK58** [comment]
<img width="344" alt="Screenshot 2022-04-25 at 17 16 18" src="https://user-images.githubusercontent.com/35194489/165119579-25ee3f11-adad-4720-8ddd-c9e5550ab0e0.png">

Aktueller main branch

**Comment by KaiWissel** [comment]
@JEK58 After merging my last PR into main?
I encountered the problem when running admin.spec -> test delete flight; This causes the error not any longer on my system.

**Comment by KaiWissel** [comment]
cb0c6b3cdea3adb90a950bd7e98cb8a6d5adc056

**Comment by JEK58** [comment]
Yep was after that merge. Will evaluate further.
