### ISSUE TITLE
Antwortkommentare mit Text "[object Object]"

### ISSUE THREAD

**Issue by vindolin** [XCCup/xccup.net#453]
Antwortkommentare führen zu eigenständigen Kommentaren (nicht im Thread) mit dem Text "[object Object]".

Ich dachte zuerst, es hätte an den Emojis gelegen, weil ich die gestern mal bei einem Kommentar weggelassen hatte und dann hatte der funktioniert.

Heute habe ich das selbe Problem aber auch mit Kommentaren ohne Emoji.
![image](https://user-images.githubusercontent.com/834347/167290366-373cd178-f8a2-4cfd-8e51-f39017c906c9.png)

Browser: Firefox 99.0.1

**Comment by JEK58** [comment]
fixed
