### ISSUE TITLE
Menues not working in Firefox Mobile.

### ISSUE THREAD

**Issue by vindolin** [XCCup/xccup.net#456]
Menue items are not clickable in FFM.

Main items can be expanded but a click on the nodes does nothing.

**Comment by KaiWissel** [comment]
@vindolin Which OS and Firefox Version are in use? All menu items or only the "user button"?

Can't confirm on Samsung A52, Android 12 and FFM 100.1.1

**Comment by vindolin** [comment]
Xiaomi MIUI 13, Android 12, FFM 100.1.1 

Works perfectly on Chrome on the same phone.

**Comment by vindolin** [comment]
No idea why, but now it's working under FFM 100.3.0 🤷‍♂️
