### ISSUE TITLE
Multiple requests and DB queries when reloading admin view

### ISSUE THREAD

**Issue by KaiWissel** [XCCup/xccup.net#491]
![grafik](https://user-images.githubusercontent.com/42967368/169895375-396e4ec7-9fbb-4975-acf7-ff69fb214b12.png)

**Comment by JEK58** [comment]
Admin notification fetch has been limited in https://github.com/XCCup/xccup.net/pull/494

Apart from that I can see no recurring api calls.

https://user-images.githubusercontent.com/35194489/169970001-750ad564-7d68-438d-b55e-bbdbb9d87c4a.mov
