### ISSUE TITLE
429 Too Many Requests Error after trying to delete image then uploading another one.

### ISSUE THREAD

**Issue by vindolin** [XCCup/xccup.net#553]
![image](https://user-images.githubusercontent.com/834347/184857649-9eac0d49-ca32-4358-9a2b-ee8d622ad79b.png)

I tried to change one photo for a flight and always get this error after selecting a file.

**Comment by JEK58** [comment]
Can you please provide the flight id or link to the flight?

**Comment by vindolin** [comment]
Here you go: [75760](https://xccup.net/flug/75760/bearbeiten)

**Comment by JEK58** [comment]
:D:D:D

<img width="511" alt="Screenshot 2022-08-16 at 18 27 41" src="https://user-images.githubusercontent.com/35194489/184931096-eeee1cec-23d3-4e8e-be51-b81db8976f23.png">

It's the limitation to 8 photos per flight. And as you can see in the comment. Someone already noticed that this may be a misleading error message;)

Will fix in future:)

@KaiWissel Shall we increase the max photos limit? 9 would at least UI wise make more sense.
Or even 12.

**Comment by vindolin** [comment]
But I tried to delete one of the eight images and upload a new one in one step.

**Comment by JEK58** [comment]
That's because the photo only gets deleted if you click save. Otherwise the photo would be gone even if you click on cancel.
But it's clearly bad UX and will be fixed.

**Comment by KaiWissel** [comment]
> :D:D:D
> 
> <img width="511" alt="Screenshot 2022-08-16 at 18 27 41" src="https://user-images.githubusercontent.com/35194489/184931096-eeee1cec-23d3-4e8e-be51-b81db8976f23.png">
> 
> It's the limitation to 8 photos per flight. And as you can see in the comment. Someone already noticed that this may be a misleading error message;)
> 
> Will fix in future:)
> 
> @KaiWissel Shall we increase the max photos limit? 9 would at least UI wise make more sense.
> Or even 12. 
> 
> 
> 

9 sounds fine... or 6 😅
People should pick what they want to show and not blindly drop every bit they've got

**Comment by JEK58** [comment]
Fixed in https://github.com/XCCup/xccup.net/pull/555
May need refactoring in future.
