### ISSUE TITLE
Allow users to delete account from profile

### ISSUE THREAD

**Issue by JEK58** [XCCup/xccup.net#588]

**Comment by JEK58** [comment]
I, as a user want to be able to delete my profile.

**Comment by KaiWissel** [comment]
@JEK58 delete also flights of user?

**Comment by JEK58** [comment]
Good question. We could replace the username with "Gelöschter Benutzer" but the igc would still be there…
Or we delete the flight, yes. But old rankings should not be affected by that.

**Comment by KaiWissel** [comment]
- Change user name to "Deleted User"
- Change user role to "deleted"
- Remove all personal data from profile
- Replace content of comments by "deleted"
- Do not retrieve igc file
