### ISSUE TITLE
Allow to expand map vertically on desktop flight view

### ISSUE THREAD

**Issue by JEK58** [XCCup/xccup.net#603]

**Comment by JEK58** [comment]
https://github.com/XCCup/xccup.net/pull/630

**Comment by JEK58** [comment]
Make this responsive?
Like allow full 100vh on mobiles?

**Comment by KaiWissel** [comment]
Let's see what the crowd wants in the next season. For now they can play around with the new option.

**Comment by KaiWissel** [comment]
Any further requests this season @JEK58 ?
Or should we close this issue?
