### ISSUE TITLE
Eval usage of tinyfilemanager

### ISSUE THREAD

**Issue by KaiWissel** [XCCup/xccup.net#610]
https://tinyfilemanager.github.io/

**Comment by JEK58** [comment]
What for? We already have SSH & SFTP.

**Comment by KaiWissel** [comment]
"Ease of use"

**Comment by JEK58** [comment]
I don't see the use. Why expose the file system to the web when you already can access it with any (GUI)FTP client? What for?

**Comment by KaiWissel** [comment]
Because you need a ftp client installed on your system... I personally do everything with scp.
Like I mentionend in the title "evaluate" usage. It's prio z. I just stumpled upon it on work. This issue here is just a sticky note ;-)
