### ISSUE TITLE
Add Info view for auto flight upload

### ISSUE THREAD

**Issue by KaiWissel** [XCCup/xccup.net#767]
Howto Auto Upload from
- Skytraxx 
- Flymaster

I received several question about it in the last coupe days

**Comment by JEK58** [comment]
Skytraxx: No idea, maybe the skytraxx dev knows.
Flymaster: lt.flymaster.net => My Account => My Instruments => Edit => XC-Servers => Add XC-Server => Select XCCup => Fill in credentials and activate Auto Upload
